### ISSUE TITLE
Normalization did not reach convergence 

### ISSUE THREAD

**Issue by GeorgiaBreckell** [fanglab/nanodisco#15]
Hi,

When running the difference function I am getting output such as:

` Normalization did not reach convergence for 1 read(s) on chunk #375`
` Normalization did not reach convergence for 1 read(s) on chunk #411`
`  No regional downsampling for SC12A_B2_WGA chunk #413: region too short (contig_1_pilon:2062580-2062587,+; 6 bp).  `      
`  Regional downsampling: 558 reads from SC12A_B2_WGA chunk #413 (contig_1_pilon:2061822-2065831,-; 4008 bp).`
` Localized downsampling: 54 reads from SC12A_B2_WGA chunk #413.`

Wondering what the consequences of this might be and if I might need to filter or improve the data set in someway. 

Thanks

**Comment by touala** [comment]
Hello @GeorgiaBreckell,

Those are normal output messages from a `nanodisco` analysis and I usually don't attempt to address them with additional preprocessing.
- One read is concerned by the normalization message for each chunk and I'm expecting no impact on the analysis (the iterative linear regression used during normalization has `maxit` set at 20).
- Currently, `nanodisco` apply simple rules to downsample extremely high coverage regions (>1000x) to avoid extreme ressources usage during the analysis (e.g. runtime and memory). Those commonly occur in repeat-like regions even if the average sample coverage is not extreme. We commonly observe it for short contigs in metagenomic analysis (sometimes originating from an aggregate of the host repeat elements). In addition, WGA samples are more prone to this phenomenon due to the amplification bias.

To be safe, and if you are interested in specific genomic regions, I would keep `nanodisco`'s logs and confirm that the regions of interest are not affected.

If you have any other questions about `nanodisco` usage, please feel free to reach back to us. 

Regards,

Alan
