### ISSUE TITLE
Could nanodisco detect methylation from other species

### ISSUE THREAD

**Issue by lemonsky123** [fanglab/nanodisco#2]
HI, @fanggang @jbeaulaurier ,Could nanodisco detect methylation from other species, such as human?

**Comment by touala** [comment]
Hello @lemonsky123,

Thank you for your interest in our tool. `nanodisco` is currently focused on _de novo_ discovering, typing and fine mapping methylation motifs, the key challenge that prevents broad use of nanopore sequencing for the _de novo_ study of bacterial epigenomes. We do not recommend using nanodisco to look for methylation in human because 1) in the human genome, 5mC is mostly at CpG sites, for which multiple existing tools, such as Nanopolish and Tombo, have been specifically trained; 2) for 6mA/4mC, if they exists in the human genome, it is at much lower level than 5mC, and would probably require different strategies for detection. Please see Question-7 in the FAQ page for more information: https://nanodisco.readthedocs.io/en/latest/faq.html#q-methylation-event.

Feel free to reach back to us if you have other questions.

Alan

**Comment by touala** [comment]
I'll close this issue. Feel free to reach back to us if you have other questions.

Alan
