### ISSUE TITLE
"From" values not present in "X" error

### ISSUE THREAD

**Issue by GeorgiaBreckell** [fanglab/nanodisco#20]
Hi, 

I have a group of samples which are giving me the below error during the difference command:

```
local:20/5/100%/171.8s The following `from` values were not present in `x`: -
local:20/6/100%/145.8s The following `from` values were not present in `x`: -
local:20/7/100%/127.0s The following `from` values were not present in `x`: -
```
It also appears that the chunks are skipped because the processing speeds up rapidly. 

All my datasets have been basecalled with Guppy version 4.2.2 and my other samples haven't given this error. All the samples with this error were sequenced on the same flow cell, so I do suspect this is an issue with my input data, but do you know what features of the reads would cause Nanodisco to give this error? 

Thanks

**Comment by touala** [comment]
Hi @GeorgiaBreckell,

The error message from `R` is not extremely helpful, so I'm not sure what is the problem. This could be related to missing  strand information from `nanopolish` output. Since it works on your other samples, I'm suspecting an issue with the input parameters. Could you double check that the content of input files (e.g. reads, alignments, reference) make sense?

Alternatively, if you would like to privately share a subset of fast5 files and the fasta reference file (to alan.tourancheau@bio.ens.psl.eu), it would be extremely helpful for debugging and sorting out this issue.

Alan
