### ISSUE TITLE
Potential issues with Guppy, the sup basecalling model, and barcodes

### ISSUE THREAD

**Issue by alexanderwg-ornl** [fanglab/nanodisco#28]
I'm currently attempting to do _de novo_ methylation discovery on a _Geobacillus_ species. I have in hand methylation motifs detected via PacBio, and I'm attempting to replicate this via Nanodisco. I generated WGA and native reads, but when I tried to compute differences I got through a quarter of the genome with no differences detected. Questions:

1) Does the relative read depth matter between the native and the WGA reads? I have a much shallower read depth for the WGA reads due to the reuse of a previous flowcell.
2) Do you anticipate barcodes potentially causing problems in your pipeline?
3) I'm using Guppy v5.0.14 and the dna_r9.4.1_450bps_sup.cfg calling model. Is this compatible with Nanodisco? If not, would you recommend using this highly accurate caller to produce the reference genome, then recalling it in some other version of guppy or even Albacore to produce the native and WGA basecalled fast5 files needed.

Thanks so much for your help! I very much look forward to using this wonderful tool you and your colleges have developed.

-Bill

**Comment by touala** [comment]
Hi Bill,

1. The difference in read depth between native and WGA should not matter much for the analysis, but the genomic coverage of each dataset need to be sufficient for accurate current estimation. We obtained great results when coverage is > 150x for each dataset. How deep are your datasets?
2. We systematically remove the barcodes during Guppy basecalling with `--trim_barcodes` but I don't exactly know how this affect the analysis. I would expect it to be marginal because most barcode sequences should not get aligned, and the signal/noise from remaining ones will be "diluted" in the genome wide analysis that `nanodisco` is performing. Although, if you rely on *de novo* assembly as suggested in 3., then barcodes will have more effect. I still don't think it will prevent `nanodisco` from working properly but you might get artifact in the assembly.
3. `nanodisco` is working well with Guppy `v5.0.14` and the `dna_r9.4.1_450bps_sup.cfg`. However, it doesn't like the latest fast5 format which use `vbz` compression. If your datasets were generated recently, this could explain the lack of current differences. I've just updated issue #26 with a little more information on how to identify and fix this issue. Please let me know if this is helpful. 

Alan

**Comment by alexanderwg-ornl** [comment]
Hi Alan,
  The solution you outlined in Issue #26 worked to solve my problem as well. Once I had converted from `vzb` compression, `nanodisco` ran with no problems. The methylation motifs detected by `nanodisco` precisely matched those called by previous PacBio sequencing. Thanks again for being so responsive!
