### ISSUE TITLE
Tmpdir not found with difference

### ISSUE THREAD

**Issue by Lcornet** [fanglab/nanodisco#3]
Hi,

I would like to test nano disco but I have this problem on our HPC with nanodisco difference :

parallel: Error: Tmpdir '/localscratch/lcornet/68933322' does not exist.
parallel: Error: Try 'mkdir /localscratch/lcornet/68933322'

#log
$ singularity exec nanodisco.sif nanodisco preprocess -p 20 -f ULC307-fast5/ -s ULC307 -o analysis/ULC307 -r pilon/pilon.fasta
$singularity exec nanodisco.sif nanodisco chunk_info  -r pilon/pilon.fasta
Number of chunks: 6289
$ singularity exec nanodisco.sif nanodisco difference -nj 1 -nc 20 -p 20 -f 1 -l 6289 -i analysis/ULC307 -o analysis/difference_subset -w ULC307 -n ULC307 -r pilon/pilon.fasta #To run on one node but 20 chunks, each 1 cpu

Could you help me ?

**Comment by touala** [comment]
Hello @Lcornet,

Sure, we will try to sort it out.

It appears that the issue comes from `parallel` software which cannot write the cache/temporary files. Did you try to create the "missing" directory with `mkdir /localscratch/lcornet/68933322` and rerun as suggested? In my search I see that this kind of issue can happen if parallel do not have the write permission or cannot find the directory (https://www.biostars.org/p/152765/). It could also be an issue related to limited disk space. Is `/localscratch/lcornet/` full?

I also see another issue. You used `ULC307` twice in the `nanodisco difference` command. You should supply the names for the native sample with `-n ULC307_nat` and WGA sample with `-w ULC307_wga`. Those samples need to be independently preprocessed with `nanodisco preprocess` with their respective names (e.g. `-s ULC307_nat`). Our rationale for using WGA is described in our [FAQ](https://nanodisco.readthedocs.io/en/latest/faq.html#q-wga).

Please let me know if you were able to fix your issue or if you have other questions.

Alan
