### ISSUE TITLE
Error in { : task 1 failed - "object 'contig' not found"

### ISSUE THREAD

**Issue by aerijman** [fanglab/nanodisco#36]
Dear Alan,

`preprocess` worked but `difference` is throwing the error described in the title.

This is the command:
```
nanodisco difference -nj 4 -nc 1 -p 1 -f 10 -l 11 -i analysis/preprocessed_subset -o analysis/difference_subset -w b24 -n b23 -r reference/mergenome.fasta
```

And this is the standard output:
'''
Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
local:2/0/100%/0.0s Error in { : task 1 failed - "object 'contig' not found"
Calls: %do% -> <Anonymous>
Execution halted
local:1/1/100%/127.0s Error in { : task 1 failed - "object 'contig' not found"
Calls: %do% -> <Anonymous>
Execution halted
local:0/2/100%/63.5s
''' 

I am looking forward to getting your help to solve this issue.
Thank you!

**Comment by touala** [comment]
Hello @aerijman,

Were you able to diagnose the issue already? From this error message, I don't know what is the underlying issue. Early on, I encounter issue when contig names were only numerical (">1209" instead of ">contig_1209"), so maybe this is similar.

Do any output files are generated? Alternatively, you could try to run a command with likely less ressources:
```
nanodisco difference -nj 1 -nc 1 -p 1 -f 10 -l 10 ...
```

Best,

Alan

**Comment by touala** [comment]
Hello @aerijman,

Feel free to reopen if the issue is not sorted.

Best,

Alan
