### ISSUE TITLE
 Generating current differences without WGA sample 

### ISSUE THREAD

**Issue by DelphIONe** [fanglab/nanodisco#69]
Hi,

Thanks for your tool.
After reading your article, it was not clear for me that the sequencing of the WGA sample was necessary and essential to use Nanodisco, do you confirm this ?
If you trained a model from WGA samples from various bacteria I don't understand why the comparison between the current of the modified sample and your model (from the training) cannot be give good results ? 

Can you explain me please ?
Thanks again,

**Comment by touala** [comment]
Hi @DelphIONe,

Thank you for your interest in `nanodisco`. Yes, we think WGA is currently still necessary for _de novo_ discovery, typing and fine mapping bacterial DNA methylation, in a reliable and comprehensive manner.

The WGA training model you mentioned below is more complex than it may appear. The foundation is to generate a high quality, matched (meta-)genome for your sample of interest. This can be challenging with native data only, because some methylation events can affect base calling. In addition, our paper highlighted that the same type of methylation have great heterogeneous signatures, and some time very subtle in nanopore signal, so we found that it was best to compare matching raw nanopore data (native vs WGA) to get the most accurate set of modified motifs. Please also see [Q4](https://nanodisco.readthedocs.io/en/latest/faq.html) in our FAQ.

We also agree that ideally it would be better to use `nanodisco` without WGA, and we are actively trying to do so. However, currently, we do think it is necessary to have WGA for reliable and comprehensive discovery. And we are working on a R10 version as mentioned in some other QAs. 

Alan

**Comment by DelphIONe** [comment]
Hi Alan,

Thanks a lot for your quickly answer. And thanks for your FAQ (sorry I didn't read it).
It's clear :-)

**Comment by touala** [comment]
You're welcome. No worries for the FAQ.

**Comment by gin-16** [comment]
Hi Alan, looking forward to the release for the R10 version as you mention,

**Comment by gin-16** [comment]
Hi Alan, 

Thanks for developing this exciting tool. 
Regarding to the R10 version you mentioned, any thoughts on when it could be release? : ) we are very much looking forward to try it on some R10 samples we recently produced.
